# Generated by Django 5.0.7 on 2024-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('KAO', 'Kakao'), ('ORI', 'Original')], default='ORI', max_length=3),
        ),
    ]
